import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePrescriptionPDF = (prescription, patientName, doctorName) => {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 0, 210, 30, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("Clinic SaaS", 14, 13);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Medical Prescription", 14, 22);

    // Patient & Doctor Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Patient Information", 14, 42);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Patient Name: ${patientName}`, 14, 50);
    doc.text(`Doctor: ${doctorName}`, 14, 57);
    doc.text(`Date: ${new Date(prescription.createdAt?.seconds * 1000 || Date.now()).toLocaleDateString()}`, 14, 64);

    // Medicines Table
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Prescribed Medicines", 14, 78);

    autoTable(doc, {
        startY: 83,
        head: [["#", "Medicine", "Dosage", "Duration", "Instructions"]],
        body: prescription.medicines.map((m, i) => [
            i + 1,
            m.name,
            m.dosage,
            m.duration,
            m.instructions || "—",
        ]),
        styles: { fontSize: 9 },
        headStyles: { fillColor: [59, 130, 246] },
    });

    // Notes
    if (prescription.notes) {
        const finalY = doc.lastAutoTable.finalY + 10;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.text("Doctor's Notes", 14, finalY);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.text(prescription.notes, 14, finalY + 8);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Clinic SaaS — This is a computer generated prescription", 14, 285);

    doc.save(`prescription-${patientName}.pdf`);
};